import type {
  AssessmentMarksOverview,
  AssessmentsOverview,
} from "./assessments.types"

export async function fetchAssessmentsOverview(): Promise<AssessmentsOverview> {
  return {
    subject: "Data Structures",
    program: "BSc CSIT",
    semester: "Second Semester",
    subjects: ["Data Structures"],
    assessments: [
      {
        id: "asm_1",
        title: "Internal Exam I",
        kind: "exam",
        status: "marks-entered",
        totalMarks: 20,
        dateLabel: "Held 2 July",
        studentCount: 42,
        enteredCount: 42,
      },
      {
        id: "asm_2",
        title: "Assignment 2",
        kind: "assignment",
        status: "in-progress",
        totalMarks: 10,
        dateLabel: "12 July",
        studentCount: 42,
        enteredCount: 28,
      },
      {
        id: "asm_3",
        title: "Internal Exam II",
        kind: "exam",
        status: "not-started",
        totalMarks: 20,
        dateLabel: "Scheduled 28 July",
        studentCount: 42,
        enteredCount: 10,
      },
    ],
  }
}

export async function fetchAssessmentMarks(
  assessmentId: string
): Promise<AssessmentMarksOverview> {
  return {
    assessmentId,
    title: "Assignment I",
    subject: "Data Structures",
    program: "BSc CSIT",
    semester: "Second Semester",
    dateLabel: "Shrawan 2082",
    totalMarks: 20,
    students: [
      {
        id: "csit-csit-208232",
        name: "Aaryadeep Subedi",
        rollNumber: "232",
        avatarColor: "violet",
        marks: 20,
      },
      {
        id: "csit-csit-208201",
        name: "Aavash Samsher Rana",
        rollNumber: "201",
        avatarColor: "blue",
        marks: 9,
      },
      {
        id: "csit-csit-208202",
        name: "Aayush Ghimire",
        rollNumber: "202",
        avatarColor: "rose",
        marks: 15,
      },
      {
        id: "csit-csit-208203",
        name: "Aayushma Deo",
        rollNumber: "203",
        avatarColor: "green",
        marks: null,
      },
      {
        id: "csit-csit-208204",
        name: "Abdus Samad Baksh",
        rollNumber: "204",
        avatarColor: "teal",
        marks: 17,
      },
      {
        id: "csit-csit-208205",
        name: "Achyut Joshi",
        rollNumber: "205",
        avatarColor: "amber",
        marks: 6,
      },
      {
        id: "csit-csit-208206",
        name: "Adrasha Gautam",
        rollNumber: "206",
        avatarColor: "violet",
        marks: 5,
      },
      {
        id: "csit-csit-208207",
        name: "Afjal Khan",
        rollNumber: "207",
        avatarColor: "blue",
        marks: 5,
      },
      {
        id: "csit-csit-208208",
        name: "Alok Chaudhary",
        rollNumber: "208",
        avatarColor: "rose",
        marks: 19,
      },
      {
        id: "csit-csit-208209",
        name: "Aman Basnet",
        rollNumber: "209",
        avatarColor: "green",
        marks: 13,
      },
      {
        id: "csit-csit-208210",
        name: "Amrit Neupane",
        rollNumber: "210",
        avatarColor: "teal",
        marks: 13,
      },
      {
        id: "csit-csit-208211",
        name: "Anan Thapa",
        rollNumber: "211",
        avatarColor: "amber",
        marks: 19,
      },
      {
        id: "csit-csit-208212",
        name: "Archi Dahal",
        rollNumber: "212",
        avatarColor: "violet",
        marks: 18,
      },
      {
        id: "csit-csit-208213",
        name: "Aryan Thapa",
        rollNumber: "213",
        avatarColor: "blue",
        marks: 8,
      },
      {
        id: "csit-csit-208214",
        name: "Babin Bista",
        rollNumber: "214",
        avatarColor: "rose",
        marks: 13,
      },
      {
        id: "csit-csit-208215",
        name: "Bidhan Rimal",
        rollNumber: "215",
        avatarColor: "green",
        marks: 5,
      },
      {
        id: "csit-csit-208216",
        name: "Bidushi Adhikari",
        rollNumber: "216",
        avatarColor: "teal",
        marks: 17,
      },
      {
        id: "csit-csit-208217",
        name: "Bishal Gajurel",
        rollNumber: "217",
        avatarColor: "amber",
        marks: 18,
      },
      {
        id: "csit-csit-208218",
        name: "Chandan Mahato",
        rollNumber: "218",
        avatarColor: "violet",
        marks: 19,
      },
      {
        id: "csit-csit-208219",
        name: "Devin Darlami",
        rollNumber: "219",
        avatarColor: "blue",
        marks: 20,
      },
      {
        id: "csit-csit-208220",
        name: "Drabin Poorna Shrestha",
        rollNumber: "220",
        avatarColor: "rose",
        marks: 20,
      },
      {
        id: "csit-csit-208221",
        name: "Isnit Bohara",
        rollNumber: "221",
        avatarColor: "green",
        marks: 20,
      },
      {
        id: "csit-csit-208222",
        name: "Jarman RC",
        rollNumber: "222",
        avatarColor: "teal",
        marks: 18,
      },
      {
        id: "csit-csit-208223",
        name: "Kripa Gautam",
        rollNumber: "223",
        avatarColor: "amber",
        marks: 19,
      },
      {
        id: "csit-csit-208224",
        name: "Kushal Hamal",
        rollNumber: "224",
        avatarColor: "violet",
        marks: 15,
      },
      {
        id: "csit-csit-208225",
        name: "Manul Thapaliya",
        rollNumber: "225",
        avatarColor: "blue",
        marks: 15,
      },
      {
        id: "csit-csit-208226",
        name: "Mision Parajuli",
        rollNumber: "226",
        avatarColor: "rose",
        marks: 18,
      },
      {
        id: "csit-csit-208227",
        name: "Nirjal Bhatta",
        rollNumber: "227",
        avatarColor: "green",
        marks: 7,
      },
      {
        id: "csit-csit-208228",
        name: "Nischal Raj Hamal Thakuri",
        rollNumber: "228",
        avatarColor: "teal",
        marks: 10,
      },
      {
        id: "csit-csit-208229",
        name: "Nistha Timalsina",
        rollNumber: "229",
        avatarColor: "amber",
        marks: 20,
      },
      {
        id: "csit-csit-208230",
        name: "Prabesh Malla",
        rollNumber: "230",
        avatarColor: "violet",
        marks: 12,
      },
      {
        id: "csit-csit-208231",
        name: "Prajal Dhakal",
        rollNumber: "231",
        avatarColor: "blue",
        marks: 12,
      },
      {
        id: "csit-csit-208233",
        name: "Rachana Karki",
        rollNumber: "233",
        avatarColor: "rose",
        marks: 19,
      },
      {
        id: "csit-csit-208234",
        name: "Rasesh Neupane",
        rollNumber: "234",
        avatarColor: "green",
        marks: 8,
      },
      {
        id: "csit-csit-208235",
        name: "Reeya Dangol",
        rollNumber: "235",
        avatarColor: "teal",
        marks: 17,
      },
      {
        id: "csit-csit-208236",
        name: "Ritesh Gyawali",
        rollNumber: "236",
        avatarColor: "amber",
        marks: 17,
      },
      {
        id: "csit-csit-208237",
        name: "Ronish Mainali",
        rollNumber: "237",
        avatarColor: "violet",
        marks: 14,
      },
      {
        id: "csit-csit-208238",
        name: "Samrina Maharjan",
        rollNumber: "238",
        avatarColor: "blue",
        marks: 18,
      },
      {
        id: "csit-csit-208239",
        name: "Sandesh Aryal",
        rollNumber: "239",
        avatarColor: "rose",
        marks: 16,
      },
      {
        id: "csit-csit-208240",
        name: "Sandesh Khadka",
        rollNumber: "240",
        avatarColor: "green",
        marks: 18,
      },
      {
        id: "csit-csit-208241",
        name: "Sashank Rupakheti",
        rollNumber: "241",
        avatarColor: "teal",
        marks: 19,
      },
      {
        id: "csit-csit-208242",
        name: "Shekhar Nath Bhattarai",
        rollNumber: "242",
        avatarColor: "amber",
        marks: 18,
      },
      {
        id: "csit-csit-208243",
        name: "Shradha Pokhrel",
        rollNumber: "243",
        avatarColor: "violet",
        marks: 16,
      },
      {
        id: "csit-csit-208244",
        name: "Shristi Bhattarai",
        rollNumber: "244",
        avatarColor: "blue",
        marks: 18,
      },
      {
        id: "csit-csit-208245",
        name: "Subodh Pandey",
        rollNumber: "245",
        avatarColor: "rose",
        marks: 5,
      },
      {
        id: "csit-csit-208246",
        name: "Sudiksha Shrestha",
        rollNumber: "246",
        avatarColor: "green",
        marks: 19,
      },
      {
        id: "csit-csit-208247",
        name: "Sujal Subedi",
        rollNumber: "247",
        avatarColor: "teal",
        marks: 15,
      },
      {
        id: "csit-csit-208248",
        name: "Sulav G.C",
        rollNumber: "248",
        avatarColor: "amber",
        marks: 19,
      },
    ],
  }
}
